version: '1'
services:
  express:
    container_name: express-app-ctr
    image: express-img:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    container_name: mongodb-ctr
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data-vlm:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data-vlm: